-- SQL Schema for Supabase
-- Run these commands in your Supabase SQL Editor

-- 1. Contacts Table (for form submissions)
CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Site Content Table (for dynamic text)
CREATE TABLE IF NOT EXISTS site_content (
    section_key TEXT PRIMARY KEY,
    content TEXT NOT NULL
);

-- 3. Skills Table
CREATE TABLE IF NOT EXISTS skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- 4. Projects Table
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT DEFAULT '',
    code_url TEXT DEFAULT '',
    live_url TEXT DEFAULT ''
);

-- 5. Insert Default Content (Initial Setup)
INSERT INTO site_content (section_key, content)
VALUES 
('hero_greeting', 'Hi, I''m'),
('hero_name', 'Sanjana'),
('hero_role', 'Web Developer'),
('hero_description', 'Love creating beautiful websites.'),
('about_p1', 'CS student.'),
('about_p2', 'Passionate developer.')
ON CONFLICT (section_key) DO NOTHING;
